# Generated by Django 5.0.7 on 2024-08-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='activa_team_id',
            new_name='active_team_id',
        ),
    ]
