# Generated by Django 5.0.7 on 2024-08-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name', 'created_at']},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='name',
        ),
    ]
