# Generated by Django 5.0.7 on 2024-08-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_options_rename_title_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='memebers',
            new_name='members',
        ),
    ]
