# Generated by Django 5.0.7 on 2024-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_memebers_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('deleted', 'Deleted')], default='inactive', max_length=50),
        ),
    ]
