# Generated by Django 5.0.7 on 2024-08-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_entry_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'entries'},
        ),
    ]
